permissions:
  contents: read

jobs:
  release:
    permissions:
      contents: write
    name: Build and push images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push VPA recommender
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./vertical-pod-autoscaler
          tags: "vpa-recommender:1.0.${{ github.run_number }}"
          push: true
name: Release
on:
  push:
    branches:
      - master
